/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CriteriaResolution,
  CriteriaResolutionInterface,
} from "../../../contracts/lib/CriteriaResolution";

const _abi = [
  {
    inputs: [],
    name: "ConsiderationCriteriaResolverOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "CriteriaNotEnabledForItem",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
  {
    inputs: [],
    name: "OfferCriteriaResolverOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderCriteriaResolverOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "UnresolvedConsiderationCriteria",
    type: "error",
  },
  {
    inputs: [],
    name: "UnresolvedOfferCriteria",
    type: "error",
  },
];

const _bytecode =
  "0x60808060405234601357603a908160198239f35b600080fdfe600080fdfea264697066735822122035c161da2c5f58b501025b3ca4e2da4f32ff361d975a4b1498310e74a16b4a0264736f6c634300080e0033";

type CriteriaResolutionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CriteriaResolutionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CriteriaResolution__factory extends ContractFactory {
  constructor(...args: CriteriaResolutionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CriteriaResolution> {
    return super.deploy(overrides || {}) as Promise<CriteriaResolution>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): CriteriaResolution {
    return super.attach(address) as CriteriaResolution;
  }
  override connect(signer: Signer): CriteriaResolution__factory {
    return super.connect(signer) as CriteriaResolution__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CriteriaResolutionInterface {
    return new utils.Interface(_abi) as CriteriaResolutionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CriteriaResolution {
    return new Contract(address, _abi, signerOrProvider) as CriteriaResolution;
  }
}
