/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eip1271WalletSol from "./EIP1271Wallet.sol";
export type { eip1271WalletSol };
export type { ERC1155BatchRecipient } from "./ERC1155BatchRecipient";
export type { ExcessReturnDataRecipient } from "./ExcessReturnDataRecipient";
export type { Reenterer } from "./Reenterer";
export type { TestERC1155 } from "./TestERC1155";
export type { TestERC20 } from "./TestERC20";
export type { TestERC721 } from "./TestERC721";
export type { TestZone } from "./TestZone";
