/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export type TransferHelperItemStruct = {
  itemType: BigNumberish;
  token: string;
  identifier: BigNumberish;
  amount: BigNumberish;
};

export type TransferHelperItemStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber
] & {
  itemType: number;
  token: string;
  identifier: BigNumber;
  amount: BigNumber;
};

export interface TransferHelperInterfaceInterface extends utils.Interface {
  functions: {
    "bulkTransfer((uint8,address,uint256,uint256)[],address,bytes32)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "bulkTransfer"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bulkTransfer",
    values: [TransferHelperItemStruct[], string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bulkTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TransferHelperInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TransferHelperInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bulkTransfer(
      items: TransferHelperItemStruct[],
      recipient: string,
      conduitKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  bulkTransfer(
    items: TransferHelperItemStruct[],
    recipient: string,
    conduitKey: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bulkTransfer(
      items: TransferHelperItemStruct[],
      recipient: string,
      conduitKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    bulkTransfer(
      items: TransferHelperItemStruct[],
      recipient: string,
      conduitKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bulkTransfer(
      items: TransferHelperItemStruct[],
      recipient: string,
      conduitKey: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
