/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Interface__factory } from "./ERC1155Interface__factory";
export { ERC20Interface__factory } from "./ERC20Interface__factory";
export { ERC721Interface__factory } from "./ERC721Interface__factory";
