/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ConduitControllerInterface extends utils.Interface {
  functions: {
    "acceptOwnership(address)": FunctionFragment;
    "cancelOwnershipTransfer(address)": FunctionFragment;
    "createConduit(bytes32,address)": FunctionFragment;
    "getChannel(address,uint256)": FunctionFragment;
    "getChannelStatus(address,address)": FunctionFragment;
    "getChannels(address)": FunctionFragment;
    "getConduit(bytes32)": FunctionFragment;
    "getConduitCodeHashes()": FunctionFragment;
    "getKey(address)": FunctionFragment;
    "getPotentialOwner(address)": FunctionFragment;
    "getTotalChannels(address)": FunctionFragment;
    "ownerOf(address)": FunctionFragment;
    "transferOwnership(address,address)": FunctionFragment;
    "updateChannel(address,address,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "cancelOwnershipTransfer"
      | "createConduit"
      | "getChannel"
      | "getChannelStatus"
      | "getChannels"
      | "getConduit"
      | "getConduitCodeHashes"
      | "getKey"
      | "getPotentialOwner"
      | "getTotalChannels"
      | "ownerOf"
      | "transferOwnership"
      | "updateChannel"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOwnershipTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createConduit",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannel",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannelStatus",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getChannels", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getConduit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConduitCodeHashes",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getKey", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPotentialOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalChannels",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "ownerOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateChannel",
    values: [string, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOwnershipTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createConduit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChannel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChannelStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConduit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConduitCodeHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPotentialOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateChannel",
    data: BytesLike
  ): Result;

  events: {
    "NewConduit(address,bytes32)": EventFragment;
    "OwnershipTransferred(address,address,address)": EventFragment;
    "PotentialOwnerUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewConduit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PotentialOwnerUpdated"): EventFragment;
}

export interface NewConduitEventObject {
  conduit: string;
  conduitKey: string;
}
export type NewConduitEvent = TypedEvent<
  [string, string],
  NewConduitEventObject
>;

export type NewConduitEventFilter = TypedEventFilter<NewConduitEvent>;

export interface OwnershipTransferredEventObject {
  conduit: string;
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PotentialOwnerUpdatedEventObject {
  newPotentialOwner: string;
}
export type PotentialOwnerUpdatedEvent = TypedEvent<
  [string],
  PotentialOwnerUpdatedEventObject
>;

export type PotentialOwnerUpdatedEventFilter =
  TypedEventFilter<PotentialOwnerUpdatedEvent>;

export interface ConduitController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConduitControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      conduit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelOwnershipTransfer(
      conduit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createConduit(
      conduitKey: BytesLike,
      initialOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getChannel(
      conduit: string,
      channelIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { channel: string }>;

    getChannelStatus(
      conduit: string,
      channel: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOpen: boolean }>;

    getChannels(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<[string[]] & { channels: string[] }>;

    getConduit(
      conduitKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { conduit: string; exists: boolean }>;

    getConduitCodeHashes(
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { creationCodeHash: string; runtimeCodeHash: string }
    >;

    getKey(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<[string] & { conduitKey: string }>;

    getPotentialOwner(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<[string] & { potentialOwner: string }>;

    getTotalChannels(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { totalChannels: BigNumber }>;

    ownerOf(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>;

    transferOwnership(
      conduit: string,
      newPotentialOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateChannel(
      conduit: string,
      channel: string,
      isOpen: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    conduit: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelOwnershipTransfer(
    conduit: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createConduit(
    conduitKey: BytesLike,
    initialOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getChannel(
    conduit: string,
    channelIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getChannelStatus(
    conduit: string,
    channel: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getChannels(conduit: string, overrides?: CallOverrides): Promise<string[]>;

  getConduit(
    conduitKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<[string, boolean] & { conduit: string; exists: boolean }>;

  getConduitCodeHashes(
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { creationCodeHash: string; runtimeCodeHash: string }
  >;

  getKey(conduit: string, overrides?: CallOverrides): Promise<string>;

  getPotentialOwner(
    conduit: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getTotalChannels(
    conduit: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ownerOf(conduit: string, overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    conduit: string,
    newPotentialOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateChannel(
    conduit: string,
    channel: string,
    isOpen: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(conduit: string, overrides?: CallOverrides): Promise<void>;

    cancelOwnershipTransfer(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createConduit(
      conduitKey: BytesLike,
      initialOwner: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getChannel(
      conduit: string,
      channelIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getChannelStatus(
      conduit: string,
      channel: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getChannels(conduit: string, overrides?: CallOverrides): Promise<string[]>;

    getConduit(
      conduitKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { conduit: string; exists: boolean }>;

    getConduitCodeHashes(
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { creationCodeHash: string; runtimeCodeHash: string }
    >;

    getKey(conduit: string, overrides?: CallOverrides): Promise<string>;

    getPotentialOwner(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getTotalChannels(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerOf(conduit: string, overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      conduit: string,
      newPotentialOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateChannel(
      conduit: string,
      channel: string,
      isOpen: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NewConduit(address,bytes32)"(
      conduit?: null,
      conduitKey?: null
    ): NewConduitEventFilter;
    NewConduit(conduit?: null, conduitKey?: null): NewConduitEventFilter;

    "OwnershipTransferred(address,address,address)"(
      conduit?: string | null,
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      conduit?: string | null,
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PotentialOwnerUpdated(address)"(
      newPotentialOwner?: string | null
    ): PotentialOwnerUpdatedEventFilter;
    PotentialOwnerUpdated(
      newPotentialOwner?: string | null
    ): PotentialOwnerUpdatedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      conduit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelOwnershipTransfer(
      conduit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createConduit(
      conduitKey: BytesLike,
      initialOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getChannel(
      conduit: string,
      channelIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChannelStatus(
      conduit: string,
      channel: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChannels(conduit: string, overrides?: CallOverrides): Promise<BigNumber>;

    getConduit(
      conduitKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConduitCodeHashes(overrides?: CallOverrides): Promise<BigNumber>;

    getKey(conduit: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPotentialOwner(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalChannels(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerOf(conduit: string, overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      conduit: string,
      newPotentialOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateChannel(
      conduit: string,
      channel: string,
      isOpen: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      conduit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelOwnershipTransfer(
      conduit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createConduit(
      conduitKey: BytesLike,
      initialOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getChannel(
      conduit: string,
      channelIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChannelStatus(
      conduit: string,
      channel: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChannels(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConduit(
      conduitKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConduitCodeHashes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKey(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPotentialOwner(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalChannels(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerOf(
      conduit: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      conduit: string,
      newPotentialOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateChannel(
      conduit: string,
      channel: string,
      isOpen: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
