/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PausableZoneControllerInterface } from "./PausableZoneControllerInterface";
export type { PausableZoneEventsAndErrors } from "./PausableZoneEventsAndErrors";
export type { PausableZoneInterface } from "./PausableZoneInterface";
