/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AmountDerivationErrors,
  AmountDerivationErrorsInterface,
} from "../../../contracts/interfaces/AmountDerivationErrors";

const _abi = [
  {
    inputs: [],
    name: "InexactFraction",
    type: "error",
  },
];

export class AmountDerivationErrors__factory {
  static readonly abi = _abi;
  static createInterface(): AmountDerivationErrorsInterface {
    return new utils.Interface(_abi) as AmountDerivationErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AmountDerivationErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AmountDerivationErrors;
  }
}
