/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EIP1271Interface,
  EIP1271InterfaceInterface,
} from "../../../contracts/interfaces/EIP1271Interface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "digest",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class EIP1271Interface__factory {
  static readonly abi = _abi;
  static createInterface(): EIP1271InterfaceInterface {
    return new utils.Interface(_abi) as EIP1271InterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EIP1271Interface {
    return new Contract(address, _abi, signerOrProvider) as EIP1271Interface;
  }
}
