/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SignatureVerificationErrors,
  SignatureVerificationErrorsInterface,
} from "../../../contracts/interfaces/SignatureVerificationErrors";

const _abi = [
  {
    inputs: [],
    name: "BadContractSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
    ],
    name: "BadSignatureV",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignature",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSigner",
    type: "error",
  },
];

export class SignatureVerificationErrors__factory {
  static readonly abi = _abi;
  static createInterface(): SignatureVerificationErrorsInterface {
    return new utils.Interface(_abi) as SignatureVerificationErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SignatureVerificationErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SignatureVerificationErrors;
  }
}
