/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Interface } from "./ERC1155Interface";
export type { ERC20Interface } from "./ERC20Interface";
export type { ERC721Interface } from "./ERC721Interface";
