/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  NFTApprovalInterface,
  NFTApprovalInterfaceInterface,
} from "../../../../contracts/test/EIP1271Wallet.sol/NFTApprovalInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class NFTApprovalInterface__factory {
  static readonly abi = _abi;
  static createInterface(): NFTApprovalInterfaceInterface {
    return new utils.Interface(_abi) as NFTApprovalInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTApprovalInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NFTApprovalInterface;
  }
}
